### ISSUE TITLE
 ERR wrong number of arguments for HMSET

### ISSUE THREAD

**Issue by cynosureabu** [mranney/node_redis#717]
I keep randomly receive 	" ERR wrong number of arguments for HMSET" exception. But I have wrap all the hmset calls with try catch:
```
 logger.debug('redis hmset ', cacheKey);
                try {
                    cache.hmset(cacheKey, count);
                    logger.debug('redis hmset succesfully');
                } catch (e) {
                    logger.error(e + 'cacheKey is ' + cacheKey + ' count is ', count);
                }
```
 but I still get uncaught exception as below:

```
stack		[15]
0	:	Error: ERR wrong number of arguments for HMSET
1	:	    at ReplyParser.<anonymous> (home/node_modules/redis/index.js:317:31)
2	:	    at ReplyParser.emit (events.js:95:17)
3	:	    at ReplyParser.send_error (/home/node_modules/redis/lib/parser/javascript.js:296:10)
4	:	    at ReplyParser.execute (/home/node_modules/redis/lib/parser/javascript.js:181:22)
5	:	    at RedisClient.on_data (/home/node_modules/redis/index.js:547:27)
6	:	    at Socket.<anonymous> (/home/node_modules/redis/index.js:102:14)
7	:	    at Socket.emit (events.js:95:17)
8	:	    at Socket.<anonymous> (_stream_readable.js:764:14)
9	:	    at Socket.emit (events.js:92:17)
10	:	    at emitReadable_ (_stream_readable.js:426:10)
11	:	    at emitReadable (_stream_readable.js:422:5)
12	:	    at readableAddChunk (_stream_readable.js:165:9)
13	:	    at Socket.Readable.push (_stream_readable.js:127:10)
14	:	    at TCP.onread (net.js:528:21)
level	:	error
message	:	uncaughtException: ERR wrong number of arguments for HMSET
```

Any idea?

**Comment by brycebaril** [comment]
the `try/catch` construct does not work on asynchronous calls like this. This error is a protocol error from your HMSET use being incorrect, but what happens in your code snippet is

1. the first `logger.debug` call
2. the `try` block begins
3. the outgoing HMSET call to redis is made
4. the `logger.debug` call is made
5. the `try` block finishes with no exception
6. the `catch` block is skipped because there was no exception
7. the javascript execution context completes and waits for an event
... ~miliseconds later
8. the network reply from Redis with the error returns, and is found to be an error by the parser
9. the parser sends the error to the client which then throws it

By the time the error is thrown in 9, the catch block is long since done. You cannot catch errors like this in node with asynchronous events.

The correct syntax for HMSET is `HMSET key field value` -- you're missing the `field` key.

**Comment by cynosureabu** [comment]
I am using this function:
client.hmset(hash, obj, [callback])
so the count is actually a json object. In order to figure out which field is actually missing, can I do something like:
client.hmset(cacheKey, count,function(err, reply){
 logger.error(err,cacheKey,count)
});

Thanks,

**Comment by brycebaril** [comment]
That will likely help -- most likely your object is an empty object `{}` e.g.
```
> c.hmset("foobar", {}, console.log)
true
> [Error: ERR wrong number of arguments for 'hmset' command]
```
