### ISSUE TITLE
Crash / Exception in High Frequency Read & Write

### ISSUE THREAD

**Issue by aphorise** [mranney/node_redis#745]
I'm doing a simulation to explore occurrences between Master / Slaves and involving a sentinel in worse case scenario's where any specific Redis may be unplugged. 

I'm using a short interval based timer on `180ms` or less - in which a GET & SET operation is performed - however occasionally or every so often - particularly with intervals lower than `100ms` - I get the following:
```javascript
/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:173
                    throw callback_err;
                          ^
ReferenceError: ommand_obj is not defined
    at RedisClient.flush_and_error (/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:170:17)
    at RedisClient.on_error (/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:192:10)
    at Socket.<anonymous> (/home/mehdi/git/redis-sentinel-sim/node_modules/redis/index.js:107:14)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
```

I have callbacks for all connection events & .get / .set - as well as ```try{} catch(e){}``` blocks - however I still encounter the above which causes my node.js application to crash.

The following: [redis-crash.js](https://github.com/aphorise/redis-sentinel-sim/blob/master/redis-crash.js) - which is currently on `1000ms` is what I'm using.

Am I experiencing a bug? - or perhaps an erroneous approach on my part?

**Comment by brycebaril** [comment]
Hi @aphorise -- looking into this. In this line of the error: `ReferenceError: ommand_obj is not defined` -- is that a paste error or does the error text actually say `ommand_obj` instead of `command_obj`

What version of node_redis are you using for this test?

In terms of the try/catch blocks, you cannot catch an exception thrown in an asynchronous context.

```js
try {
  some_async_function(args, callback) // function call *schedules* async work
} catch (e) {  // catch is then run synchronously after the *schedule*
  // handle error?  // nothing to catch because the schedule didn't throw
} 
// then we keep running anymore synchronous javascript here
```

then time passes and the async callback is executed.
```js
// running callback, oops callback throws -- catch has already completed
```

When providing a callback to an asynchronous function, you're giving it code to run in the future, but then all of the subsequent synchronous code executes. The callback is simply "scheduled" to run when the asynchronous event occurs.

As for if you're experiencing a bug -- it's possible. Nothing you're specifically doing should throw that error. However if it's not a paste error, I'm also not seeing anything or any version of this library that has `ommand_obj` in it...

**Comment by brycebaril** [comment]
For what it's worth -- I ran your code for a number of minutes and never had any errors

**Comment by aphorise** [comment]
@brycebaril Thanks very much for your response / input. 

Indeed - you're correct with regards to ```ommand_obj```. In an attempt to better understand inner workings of this module I had corrupted the source. I started anew (```npm install```) - and can happily confirm that even with a 1ms timer / delay in consecutive ```set``` & ```get``` no issues were exerpainced and switch-over to slaves via (```npm```) ```redis-sentinel``` occure as described and expected. 

Thank you once again - much obligied.
